// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtc0I52vaNjBY8N0D3rexd8tOfMtY9nq4',
    appId: '1:25533330565:web:485af410a1c2664b2225ec',
    messagingSenderId: '25533330565',
    projectId: 'psicocita-67794',
    authDomain: 'psicocita-67794.firebaseapp.com',
    databaseURL: 'https://psicocita-67794-default-rtdb.firebaseio.com',
    storageBucket: 'psicocita-67794.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuWfdcg6wLZ83CKNLizrhVakyqzT4_jzA',
    appId: '1:25533330565:android:c4936f46524bbec12225ec',
    messagingSenderId: '25533330565',
    projectId: 'psicocita-67794',
    databaseURL: 'https://psicocita-67794-default-rtdb.firebaseio.com',
    storageBucket: 'psicocita-67794.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpgXUTcDaa0ODTBFdrAiUWaOLYbqlMi7U',
    appId: '1:25533330565:ios:13777aadb34a0b202225ec',
    messagingSenderId: '25533330565',
    projectId: 'psicocita-67794',
    databaseURL: 'https://psicocita-67794-default-rtdb.firebaseio.com',
    storageBucket: 'psicocita-67794.appspot.com',
    iosClientId: '25533330565-avqnm459m3bebfh5cidip8u6b66m31qa.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpgXUTcDaa0ODTBFdrAiUWaOLYbqlMi7U',
    appId: '1:25533330565:ios:13777aadb34a0b202225ec',
    messagingSenderId: '25533330565',
    projectId: 'psicocita-67794',
    databaseURL: 'https://psicocita-67794-default-rtdb.firebaseio.com',
    storageBucket: 'psicocita-67794.appspot.com',
    iosClientId: '25533330565-avqnm459m3bebfh5cidip8u6b66m31qa.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyecto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtc0I52vaNjBY8N0D3rexd8tOfMtY9nq4',
    appId: '1:25533330565:web:78246f7632351cad2225ec',
    messagingSenderId: '25533330565',
    projectId: 'psicocita-67794',
    authDomain: 'psicocita-67794.firebaseapp.com',
    databaseURL: 'https://psicocita-67794-default-rtdb.firebaseio.com',
    storageBucket: 'psicocita-67794.appspot.com',
  );
}
